export const useCategories = () => {
  return [
    { label: "All", query: "all", id: 1 },
    { label: "Latest", query: "latest", id: 2 },
    { label: "Trending", query: "trending", id: 3 },
    { label: "Tech", query: "tech", id: 4 },
    { label: "Science", query: "science", id: 5 },
    { label: "Fictions", query: "fictions", id: 6 },
    { label: "Politics", query: "politics", id: 7 },
    { label: "Top Headlines", query: "top-headlines", id: 8 },
    { label: "Business", query: "business", id: 9 },
    { label: "Sports", query: "sports", id: 10 },
    { label: "World", query: "world", id: 11 },
    { label: "Local", query: "local", id: 12 },
    { label: "National", query: "national", id: 13 },
    { label: "International", query: "international", id: 14 },
    { label: "Breaking News", query: "breaking-news", id: 15 },
    { label: "Technology", query: "technology", id: 16 },
    { label: "Startups", query: "startups", id: 17 },
    { label: "Ai & Robotics", query: "ai-robotics", id: 18 },
    { label: "Space", query: "space", id: 19 },
    { label: "Gadgets", query: "gadgets", id: 20 },
    { label: "Research", query: "research", id: 21 },
    { label: "Health", query: "health", id: 22 },
    { label: "Fitness", query: "fitness", id: 23 },
    { label: "Fashion", query: "fashion", id: 24 },
    { label: "Food", query: "food", id: 25 },
    { label: "Travel", query: "travel", id: 26 },
    { label: "Art Culture", query: "art-culture", id: 27 },
    { label: "Movies", query: "movies", id: 28 },
    { label: "Music", query: "music", id: 29 },
  ];
};
